resources:
  - name: NS_P_DockerPush_0014
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/windowsimage  
      branches:
        include: master

pipelines:
  - name: NS_P_DockerPush_0014
    configuration:
      nodePool: win_2019
    steps:
      - name: NS_P_DockerPush_0014_01
        type: DockerBuild
        configuration:
          affinityGroup: NS_P_DockerPush_0014
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/img
          dockerImageTag: ${run_number}
          integrations:
            - name: art_v
          inputResources:
            - name: NS_P_DockerPush_0014
            
      - name: NS_P_DockerPush_0014_02
        type: DockerPush
        execution:
            onStart:
                - echo "prepare for main execution"
        configuration:
          affinityGroup: NS_P_DockerPush_0014
          targetRepository: rak_docker 
          integrations:
            - name: art_v 
          inputSteps:
            - name: NS_P_DockerPush_0014_01  
          
