resources:
  - name: NS_P_DockerBuild_0023
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/windowsimage   
      branches:
        include: master

pipelines:
  - name: NS_P_DockerBuild_0023
    configuration:
      nodePool: win_2019
    steps:
      - name: NS_P_DockerBuild_0023
        type: DockerBuild
        execution:
            onFailure:
                - echo "uh oh, something went wrong"
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/img
          dockerImageTag: ${run_number}
          integrations:
            - name: art_v
          inputResources:
            - name: NS_P_DockerBuild_0023
            
     