resources:
  - name: NS_P_DockerPush_0023
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/windowsimage  
      branches:
        include: master

pipelines:
  - name: NS_P_DockerPush_0023
    configuration:
      nodePool: win_2019
    steps:
      - name: NS_P_DockerPush_0023_01
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/img
          dockerImageTag: group
          integrations:
            - name: art_v
          inputResources:
            - name: NS_P_DockerPush_0023
            
      - name: NS_P_DockerPush_0023_02
        type: DockerPush
        configuration:
          targetRepository: rak_docker 
          affinityGroup: NS_P_DockerPush_0023
          integrations:
            - name: art_v 
          inputSteps:
            - name: NS_P_DockerPush_0023_01  
        