resources:
  - name: NS_P_DockerPush_0021
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/windowsimage  
      branches:
        include: master

pipelines:
  - name: NS_P_DockerPush_0021
    configuration:
      nodePool: win_2019
    steps:
      - name: NS_P_DockerPush_0021_01
        type: DockerBuild
        configuration:
          affinityGroup: NS_P_DockerPush_0021
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/img
          dockerImageTag: ${run_number}
          integrations:
            - name: art_v
          inputResources:
            - name: NS_P_DockerPush_0021
            
      - name: NS_P_DockerPush_0021_02
        type: DockerPush
        configuration:
          affinityGroup: NS_P_DockerPush_0021
          targetRepository: ""
          integrations:
            - name: art_v
          inputSteps:
            - name: NS_P_DockerPush_0021_01  
          
