resources:
  - name: NS_P_DockerPush_0003
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/windowsimage  
      branches:
        include: master
 

pipelines:
  - name: NS_P_DockerPush_0003
    configuration:
      nodePool: win_2019
    steps:
      - name: NS_P_DockerPush_0003_01
        type: DockerBuild
        configuration:
          affinityGroup: NS_P_DockerPush_0003
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/img
          dockerImageTag: ${run_number}
          integrations:
            - name: art_v
          inputResources:
            - name: NS_P_DockerPush_0003
            
      - name: NS_P_DockerPush_0003_02
        type: DockerPush
        configuration:
          affinityGroup: NS_P_DockerPush_0003
          autoPublishBuildInfo: true 
          targetRepository: rak_docker 
          integrations:
            - name: art_v 
          inputSteps:
            - name: NS_P_DockerPush_0003_01  
         
