resources:
  - name: NS_P_DockerPush_0001
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/windowsimage  
      branches:
        include: master

pipelines:
  - name: NS_P_DockerPush_0001
    configuration:
      nodePool: win_2019
    steps:
      - name: NS_P_DockerPush_0001_01
        type: DockerBuild
        configuration:
          affinityGroup: NS_P_DockerPush_0001
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/img
          dockerImageTag: ${run_number}
          integrations:
            - name: art_v
          inputResources:
            - name: NS_P_DockerPush_0001
            
      - name: NS_P_DockerPush_0001_02
        type: DockerPush
        configuration:
          affinityGroup: NS_P_DockerPush_0001
          autoPublishBuildInfo: false
          forceXrayScan: false
          targetRepository: rak_docker 
          integrations:
            - name: art_v 
          inputSteps:
            - name: NS_P_DockerPush_0001_01  