resources:
  - name: NS_P_DockerBuild_0004
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/windowsimage   
      branches:
        include: master

pipelines:
  - name: NS_P_DockerBuild_0004
    configuration:
      nodePool: win_2019
    steps:
      - type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/img
          dockerImageTag: ${run_number}
          integrations:
            - name: art_v
          inputResources:
            - name: NS_P_DockerBuild_0004
            
     