resources:
  - name: NS_P_DockerPush_0008
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/windowsimage  
      branches:
        include: master
 

pipelines:
  - name: NS_P_DockerPush_0008
    configuration:
      nodePool: win_2019
    steps:
      - name: NS_P_DockerPush_0008_01
        type: DockerBuild
        configuration:
          affinityGroup: NS_P_DockerPush_0008
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/img
          dockerImageTag: ${run_number}
          integrations:
            - name: art_v
          inputResources:
            - name: NS_P_DockerPush_0008
            
      - name: NS_P_DockerPush_0008_02
        type: DockerInvalid
        configuration:
          affinityGroup: NS_P_DockerPush_0008
          targetRepository: rak_docker 
          integrations:
            - name: art_v
          inputSteps:
            - name: NS_P_DockerPush_0008_01  
         
