resources:
  - name: NS_P_DockerBuild_0013
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/windowsimage   
      branches:
        include: master

pipelines:
  - name: NS_P_DockerBuild_0013
    configuration:
      nodePool: win_2019
    steps:
      - name: NS_P_DockerBuild_0013
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile_01
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/img
          dockerImageTag: ${run_number}
          integrations:
            - name: art_v
          inputResources:
            - name: NS_P_DockerBuild_0013
            
     