resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/windowsimage  
      branches:
        include: master
  - name: NS_P_DockerPush_0002
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: NS_P_DockerPush_0002
      buildNumber: 1

pipelines:
  - name: NS_P_DockerPush_0002
    configuration:
      nodePool: win_2019
    steps:
      - name: NS_P_DockerPush_0002_01
        type: DockerBuild
        configuration:
          affinityGroup: Together
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/img
          dockerImageTag: group
          integrations:
            - name: art_v
          inputResources:
            - name: dbp_repo
            
      - name: NS_P_DockerPush_0002_02
        type: DockerPush
        configuration:
          autoPublishBuildInfo: true
#           forceXrayScan: true
          targetRepository: rak_docker 
#           affinityGroup: Together
          integrations:
            - name: art_v 
          inputSteps:
            - name: NS_P_DockerPush_0002_01  
          outputResources:
            - name: NS_P_DockerPush_0002
