resources:
  - name: dbp_repo_02
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                      # <-- replace with your integration
      path: raksha78/windowsimage   # <-- replace with your repository name
      branches:
        include: master

  - name: dbp_build_info_02
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: dbp_build_rak_2
      buildNumber: 2
            

pipelines:
  - name: rak_test_pipe
    configuration:
      nodePool: win_2019
    steps:
      - name: build_Docker_Image
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/win
          dockerImageTag: latest
          integrations:
            - name: art_vv
          inputResources:
            - name: dbp_repo_02
            
      - name: Push_Docker_Image
        type: DockerPush
        configuration:
          autoPublishBuildInfo: false #IMPORTANGT******************* : if this is true then only we need outputResource in DockerPush and no need of publishBuildInfo step
          targetRepository: rak_docker #required
          integrations:
            - name: art_v 
          inputSteps:
            - name: build_Docker_Image  
