resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/windowsimage  
      branches:
        include: master

pipelines:
  - name: NS_P_DockerPush_0001
    configuration:
      nodePool: win_2019
    steps:
      - name: NS_P_DockerPush_0001_01
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/img
          dockerImageTag: latest
          integrations:
            - name: art_v
          inputResources:
            - name: dbp_repo
            
      - name: NS_P_DockerPush_0001_02
        type: DockerPush
        configuration:
          autoPublishBuildInfo: false
          forceXrayScan: false
          targetRepository: rak_docker 
          integrations:
            - name: art_v 
          inputSteps:
            - name: NS_P_DockerPush_0001_01  

            
